###############################################################################
# DD
# Author: Aldrin Magno
# Created: 04/12/18
###############################################################################
version: "3"
services:
    mariadb:
      image: mariadb:10.4
      networks:
        - backend
      container_name: dd-mariadb
      volumes:
        - /var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=thispasswordsuckstoo
        - MYSQL_DATABASE=drupal
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=thispasswordsuckstoo
      ports:
        - "8082:3306"
        
    phpmyadmin:
      image: phpmyadmin/phpmyadmin:4.7
      container_name: dd-phpmyadmin
      ports:
        - 8083:80
      links:
        - mariadb
      environment:
        PMA_HOST: mariadb

    webserver:
      build: phpdocker/httpd
      depends_on:
        - php-fpm
        - mariadb
      links:
        - php-fpm
      networks:
        - backend
      container_name: dd-webserver
      working_dir: /drupal
      volumes:
        - ./drupal/modules:/usr/local/apache2/htdocs/drupal1/web/modules
        - ./drupal/themes:/usr/local/apache2/htdocs/drupal1/web/themes
        - drupal-volume:/usr/local/apache2/htdocs/drupal1
      ports:
        - "8080:80"

    php-fpm:
      build: phpdocker/php-fpm
      networks:
        - backend
      container_name: dd-php-fpm
      working_dir: /drupal
      volumes:
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
        - ./drupal/modules:/usr/local/apache2/htdocs/drupal1/web/modules
        - ./drupal/themes:/usr/local/apache2/htdocs/drupal1/web/themes
        - drupal-volume:/usr/local/apache2/htdocs/drupal1
networks:
  backend:
    
volumes:
  drupal-volume:
